
title: Carlos
twitter_username: jekyllrb
github_username:  CarlosEscuderoBejerano

remote_theme: "mmistakes/jekyll-theme-basically-basic@1.4.5"
plugins:
  - jekyll-feed

defaults:
  # _posts
  - scope:
      path: "_posts"
      type: posts
    values:
      layout: post
      read_time: true